/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : Time,
  'author' : string,
  'excerpt' : string,
  'category' : Category,
}
export interface Booking {
  'name' : string,
  'email' : string,
  'serviceInterest' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export type Category = { 'visa' : null } |
  { 'immigrationLaw' : null } |
  { 'study' : null } |
  { 'employment' : null } |
  { 'citizenship' : null };
export interface ContactInquiry {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface Testimonial {
  'service' : string,
  'review' : string,
  'country' : string,
  'name' : string,
  'rating' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'addTestimonial' : ActorMethod<
    [string, string, number, string, string],
    undefined
  >,
  'createBlogPost' : ActorMethod<
    [string, string, string, Category, string],
    bigint
  >,
  'createConsultationBooking' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'createContactInquiry' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllConsultations' : ActorMethod<[], Array<Booking>>,
  'getAllInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getBlogPost' : ActorMethod<[bigint], [] | [BlogPost]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];